version: '3.8'
services:
  ui:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run dev -- -p 80 -H 0.0.0.0
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
